document.write(
 "<div id=\"heading\">"
+"	<div id=\"banner\">"
+"		<a href=\"welcome.html\"><img src=\"media/images/banner.jpg\" alt=\"Vegan Nutrition Banner\" class=\"bannerImg\"></a>"
+"	</div>"
+"	<div id=\"buttons\">"
+"		<a href=\"getstarted.html\" class=\"headingButton\">Get Started</a>"
+"		<a href=\"protein.html\" class=\"headingButton\">Learn about Protein</a>"
+"		<a href=\"fat.html\" class=\"headingButton\">Learn about Fat</a>"
+"		<a href=\"carbs.html\" class=\"headingButton\">Learn about Carbs</a>"
+"		<a href=\"vitamins.html\" class=\"headingButton\">Learn about Vitamins</a>"
+"		<a href=\"fibre.html\" class=\"headingButton\">Learn about Fibre</a>"
+"		<a href=\"recipe.html\" class=\"headingButton\">Recipes</a>"
+"		<a href=\"aboutus.html\" class=\"headingButton\">About Us!</a>"
+"		<div class=\"headingDropdown\">"
+"		  <img src=\"media/images/menu.png\" onclick=\"menuClick()\" class=\"menuIcon\">"
+"		  <div id=\"myDropdown\" class=\"dropdown-content\">"
+"			<a href=\"getstarted.html\">Get Started</a>"
+"			<a href=\"protein.html\">Learn about Protein</a>	"
+"			<a href=\"fat.html\">Learn about Fat</a>"
+"			<a href=\"carbs.html\">Learn about Carbohydrate</a>"	
+"			<a href=\"fibre.html\">Learn about Fibre</a>"
+"			<a href=\"vitamins.html\">Learn about Vitamins</a>"
+"			<a href=\"recipe.html\">Recipes</a>"
+"			<a href=\"aboutus.html\">About Us!</a>"
+"		  </div>"
+"		</div>"
+"	</div>"
+"</div>"
)