document.write("<div id=\"heading\">"
+"	<div id=\"banner\">"
+"		<a href=\"welcome.html\"><img src=\"banner.jpg\" alt=\"Vegan Nutrition Banner\" class=\"bannerImg\"></a>"
+"	</div>"
+"	<div id=\"buttons\">"
+"		<a href=\"getstarted.html\" class=\"headingButton\">Get Started</a>"
+"		<a href=\"protein.html\" class=\"headingButton\">Learn about Protein</a>"
+"		<a href=\"getstarted.html\" class=\"headingButton\">Learn about Fat</a>"
+"		<a href=\"getstarted.html\" class=\"headingButton\">Learn about Carbs</a>"
+"		<a href=\"getstarted.html\" class=\"headingButton\">Learn about Vitamins</a>"
+"		<a href=\"getstarted.html\" class=\"headingButton\">Learn about Fibre</a>"
+"		<a href=\"recipe.html\" class=\"headingButton\">Recipes</a>"
+"		<a href=\"getstarted.html\" class=\"headingButton\">About Us!</a>"
+"		<div class=\"headingDropdown\">"
+"		  <img src=\"menu.png\" onclick=\"menuClick()\" class=\"menuIcon\">"
+"		  <div id=\"myDropdown\" class=\"dropdown-content\">"
+"			<a href=\"getstarted.html\">Get Started</a>"
+"			<a href=\"#\">Learn about Protein</a>	"
+"			<a href=\"#\">Learn about Fat</a>"
+"			<a href=\"#\">Learn about Carbohydrate</a>"	
+"			<a href=\"#\">Learn about Fibre</a>"
+"			<a href=\"#\">Learn about Vitamins</a>"
+"			<a href=\"#\">Recipes</a>"
+"			<a href=\"#\">About Us!</a>"
+"			</div>"
+"		</div>"
+"	</div>"
+"</div>"
)